// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/trustbloc/sidetree-core-go/pkg/api/protocol"
)

type DocumentValidator struct {
	IsValidOriginalDocumentStub        func(payload []byte) error
	isValidOriginalDocumentMutex       sync.RWMutex
	isValidOriginalDocumentArgsForCall []struct {
		payload []byte
	}
	isValidOriginalDocumentReturns struct {
		result1 error
	}
	isValidOriginalDocumentReturnsOnCall map[int]struct {
		result1 error
	}
	IsValidPayloadStub        func(payload []byte) error
	isValidPayloadMutex       sync.RWMutex
	isValidPayloadArgsForCall []struct {
		payload []byte
	}
	isValidPayloadReturns struct {
		result1 error
	}
	isValidPayloadReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *DocumentValidator) IsValidOriginalDocument(payload []byte) error {
	var payloadCopy []byte
	if payload != nil {
		payloadCopy = make([]byte, len(payload))
		copy(payloadCopy, payload)
	}
	fake.isValidOriginalDocumentMutex.Lock()
	ret, specificReturn := fake.isValidOriginalDocumentReturnsOnCall[len(fake.isValidOriginalDocumentArgsForCall)]
	fake.isValidOriginalDocumentArgsForCall = append(fake.isValidOriginalDocumentArgsForCall, struct {
		payload []byte
	}{payloadCopy})
	fake.recordInvocation("IsValidOriginalDocument", []interface{}{payloadCopy})
	fake.isValidOriginalDocumentMutex.Unlock()
	if fake.IsValidOriginalDocumentStub != nil {
		return fake.IsValidOriginalDocumentStub(payload)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.isValidOriginalDocumentReturns.result1
}

func (fake *DocumentValidator) IsValidOriginalDocumentCallCount() int {
	fake.isValidOriginalDocumentMutex.RLock()
	defer fake.isValidOriginalDocumentMutex.RUnlock()
	return len(fake.isValidOriginalDocumentArgsForCall)
}

func (fake *DocumentValidator) IsValidOriginalDocumentArgsForCall(i int) []byte {
	fake.isValidOriginalDocumentMutex.RLock()
	defer fake.isValidOriginalDocumentMutex.RUnlock()
	return fake.isValidOriginalDocumentArgsForCall[i].payload
}

func (fake *DocumentValidator) IsValidOriginalDocumentReturns(result1 error) {
	fake.IsValidOriginalDocumentStub = nil
	fake.isValidOriginalDocumentReturns = struct {
		result1 error
	}{result1}
}

func (fake *DocumentValidator) IsValidOriginalDocumentReturnsOnCall(i int, result1 error) {
	fake.IsValidOriginalDocumentStub = nil
	if fake.isValidOriginalDocumentReturnsOnCall == nil {
		fake.isValidOriginalDocumentReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.isValidOriginalDocumentReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *DocumentValidator) IsValidPayload(payload []byte) error {
	var payloadCopy []byte
	if payload != nil {
		payloadCopy = make([]byte, len(payload))
		copy(payloadCopy, payload)
	}
	fake.isValidPayloadMutex.Lock()
	ret, specificReturn := fake.isValidPayloadReturnsOnCall[len(fake.isValidPayloadArgsForCall)]
	fake.isValidPayloadArgsForCall = append(fake.isValidPayloadArgsForCall, struct {
		payload []byte
	}{payloadCopy})
	fake.recordInvocation("IsValidPayload", []interface{}{payloadCopy})
	fake.isValidPayloadMutex.Unlock()
	if fake.IsValidPayloadStub != nil {
		return fake.IsValidPayloadStub(payload)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.isValidPayloadReturns.result1
}

func (fake *DocumentValidator) IsValidPayloadCallCount() int {
	fake.isValidPayloadMutex.RLock()
	defer fake.isValidPayloadMutex.RUnlock()
	return len(fake.isValidPayloadArgsForCall)
}

func (fake *DocumentValidator) IsValidPayloadArgsForCall(i int) []byte {
	fake.isValidPayloadMutex.RLock()
	defer fake.isValidPayloadMutex.RUnlock()
	return fake.isValidPayloadArgsForCall[i].payload
}

func (fake *DocumentValidator) IsValidPayloadReturns(result1 error) {
	fake.IsValidPayloadStub = nil
	fake.isValidPayloadReturns = struct {
		result1 error
	}{result1}
}

func (fake *DocumentValidator) IsValidPayloadReturnsOnCall(i int, result1 error) {
	fake.IsValidPayloadStub = nil
	if fake.isValidPayloadReturnsOnCall == nil {
		fake.isValidPayloadReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.isValidPayloadReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *DocumentValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.isValidOriginalDocumentMutex.RLock()
	defer fake.isValidOriginalDocumentMutex.RUnlock()
	fake.isValidPayloadMutex.RLock()
	defer fake.isValidPayloadMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *DocumentValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ protocol.DocumentValidator = new(DocumentValidator)
